### PR TITLE
Opinions about changes to the Bpage

### PR DESCRIPTION
**Pull request by blueclock**
"easy to fail" It seems that fail and succeed work very differently in English

### CODE REVIEW

**Comment by mef** [comment]
and I approve this message :white_check_mark:

**Comment by blueclock** [comment]
I didn't make a changes "Mehdi is a BI consultant obsessed by architecture and design. " but I don't like people using obsessed or addicted in their bios.

I want an expert, but I want someone who is rounded, not single-minded.

**Comment by mef** [comment]
> I didn't make a changes "Mehdi is a BI consultant obsessed by architecture and design. " but I don't like people using obsessed or addicted in their bios.

A rephrase would be very welcome. The meaning I wanted to convey is that a cleanly designed (elegant, solid) solution is something I care a lot about.

**Comment by blueclock** [comment]
I think you just said it! I'll work it into another suggestion.

**Pull request merged**
