### PR TITLE
Suggestion - Lightly styled sidebar menu

### PR DESCRIPTION
**Pull request by blueclock**
Just adds a border to the top and bottom of the aside.

### CODE REVIEW

**Comment by mef** [comment]
Thanks.

I think something went wrong though:

1. the committed css is invalid: `#sidebar {` inside `#sidebar {`
2. I couldn't see any difference in the styling after fixing that: Couldn't notice the effect of the border etc.

**Comment by blueclock** [comment]
@mef you're right, sorry. Let me fix this.

**Comment by blueclock** [comment]
@mef Example 

bordered-menu

**Comment by mef** [comment]
will keep as is for the moment.

**Pull request closed without merging**
